2018-02-04T15:58:48.127+0800 I CONTROL  [initandlisten] MongoDB starting : pid=68313 port=27017 dbpath=/data/db 64-bit host=zjdeMacBook-Air.local
2018-02-04T15:58:48.128+0800 I CONTROL  [initandlisten] db version v3.4.0
2018-02-04T15:58:48.128+0800 I CONTROL  [initandlisten] git version: f4240c60f005be757399042dc12f6addbc3170c1
2018-02-04T15:58:48.128+0800 I CONTROL  [initandlisten] OpenSSL version: OpenSSL 1.0.2n  7 Dec 2017
2018-02-04T15:58:48.128+0800 I CONTROL  [initandlisten] allocator: system
2018-02-04T15:58:48.128+0800 I CONTROL  [initandlisten] modules: none
2018-02-04T15:58:48.128+0800 I CONTROL  [initandlisten] build environment:
2018-02-04T15:58:48.128+0800 I CONTROL  [initandlisten]     distarch: x86_64
2018-02-04T15:58:48.128+0800 I CONTROL  [initandlisten]     target_arch: x86_64
2018-02-04T15:58:48.128+0800 I CONTROL  [initandlisten] options: {}
2018-02-04T15:58:48.131+0800 W -        [initandlisten] Detected unclean shutdown - /data/db/mongod.lock is not empty.
2018-02-04T15:58:48.138+0800 I -        [initandlisten] Detected data files in /data/db created by the 'wiredTiger' storage engine, so setting the active storage engine to 'wiredTiger'.
2018-02-04T15:58:48.138+0800 W STORAGE  [initandlisten] Recovering data from the last clean checkpoint.
2018-02-04T15:58:48.139+0800 I STORAGE  [initandlisten] wiredtiger_open config: create,cache_size=3584M,session_max=20000,eviction=(threads_max=4),config_base=false,statistics=(fast),log=(enabled=true,archive=true,path=journal,compressor=snappy),file_manager=(close_idle_time=100000),checkpoint=(wait=60,log_size=2GB),statistics_log=(wait=0),
2018-02-04T15:58:49.582+0800 I CONTROL  [initandlisten] 
2018-02-04T15:58:49.582+0800 I CONTROL  [initandlisten] ** WARNING: Access control is not enabled for the database.
2018-02-04T15:58:49.582+0800 I CONTROL  [initandlisten] **          Read and write access to data and configuration is unrestricted.
2018-02-04T15:58:49.582+0800 I CONTROL  [initandlisten] 
2018-02-04T15:58:49.694+0800 I FTDC     [initandlisten] Initializing full-time diagnostic data capture with directory '/data/db/diagnostic.data'
2018-02-04T15:58:49.695+0800 I NETWORK  [thread1] waiting for connections on port 27017
2018-02-04T15:58:50.023+0800 I FTDC     [ftdc] Unclean full-time diagnostic data capture shutdown detected, found interim file, some metrics may have been lost. OK
2018-02-04T15:59:24.869+0800 I NETWORK  [thread1] connection accepted from 127.0.0.1:56700 #1 (1 connection now open)
2018-02-04T15:59:24.879+0800 I NETWORK  [conn1] received client metadata from 127.0.0.1:56700 conn1: { driver: { name: "PyMongo", version: "3.5.1" }, os: { type: "Darwin", name: "Darwin", architecture: "x86_64", version: "10.12.5" }, platform: "CPython 2.7.14.final.0" }
2018-02-04T15:59:24.881+0800 I NETWORK  [thread1] connection accepted from 127.0.0.1:56701 #2 (2 connections now open)
2018-02-04T15:59:24.882+0800 I NETWORK  [conn2] received client metadata from 127.0.0.1:56701 conn2: { driver: { name: "PyMongo", version: "3.5.1" }, os: { type: "Darwin", name: "Darwin", architecture: "x86_64", version: "10.12.5" }, platform: "CPython 2.7.14.final.0" }
2018-02-04T15:59:42.999+0800 I -        [conn1] end connection 127.0.0.1:56700 (2 connections now open)
2018-02-04T15:59:42.999+0800 I -        [conn2] end connection 127.0.0.1:56701 (2 connections now open)
